(import (scheme base)
        (scheme write)
        (retropikzel pffi v0-2-1 main))

(display 'int8)
(display " ")
(display (pffi-size-of 'int8))
(newline)
(display 'uint8)
(display " ")
(display (pffi-size-of 'uint8))
(newline)
(display 'int16)
(display " ")
(display (pffi-size-of 'int16))
(newline)
(display 'uint16)
(display " ")
(display (pffi-size-of 'uint16))
(newline)
(display 'int32)
(display " ")
(display (pffi-size-of 'int32))
(newline)
(display 'uint32)
(display " ")
(display (pffi-size-of 'uint32))
(newline)
(display 'int64)
(display " ")
(display (pffi-size-of 'int64))
(newline)
(display 'uint64)
(display " ")
(display (pffi-size-of 'uint64))
(newline)
(display 'char)
(display " ")
(display (pffi-size-of 'char))
(newline)
(display 'unsigned-char)
(display " ")
(display (pffi-size-of 'unsigned-char))
(newline)
(display 'short)
(display " ")
(display (pffi-size-of 'short))
(newline)
(display 'unsigned-short)
(display " ")
(display (pffi-size-of 'unsigned-short))
(newline)
(display 'int)
(display " ")
(display (pffi-size-of 'int))
(newline)
(display 'unsigned-int)
(display " ")
(display (pffi-size-of 'unsigned-int))
(newline)
(display 'long)
(display " ")
(display (pffi-size-of 'long))
(newline)
(display 'unsigned-long)
(display " ")
(display (pffi-size-of 'unsigned-long))
(newline)
(display 'float)
(display " ")
(display (pffi-size-of 'float))
(newline)
(display 'double)
(display " ")
(display (pffi-size-of 'double))
(newline)
(display 'pointer)
(display " ")
(display (pffi-size-of 'pointer))
(newline)
