image: alpine/edge
secrets:
  - 5975b08d-5ff4-4953-ab51-1a62e81e00d0
tasks:
    - trigger-jenkins-build: |
        curl --netrc-file /etc/netrc/scheme-jenkins -X POST "https://jenkins.scheme.org/job/foreign_c/job/foreign-c/job/master/build?delay=0sec"
