((packager . "retropikzel")
 (name . "r7rs-pffi")
 (version . "v0-4-1")
 (type . "library")
 (description . "Portable Foreign Function Interface for R7RS schemes")
 (license . "LGPL")
 (dependencies ()))
