FROM schemers/chibi:head
RUN apt-get update && apt-get install -y docker.io make
RUN git clone https://github.com/Retropikzel/chibi-scheme --depth=1
RUN git clone https://codeberg.org/retropikzel/test-scheme.git --depth=1
WORKDIR /chibi-scheme
RUN make && make uninstall install
WORKDIR /test-scheme
RUN snow-chibi install-dependencies test-scheme.scm
RUN make build-chibi && make install
