ARG COMPILE_R7RS=chibi
FROM schemers/sagittarius AS build
RUN apt-get update && apt-get install -y wget build-essential make cmake libgc-dev zlib1g-dev libffi-dev libssl-dev
RUN wget https://github.com/ktakashi/sagittarius-scheme/archive/refs/tags/version_0.9.12.tar.gz && tar -xf version_0.9.12.tar.gz
RUN cd sagittarius-scheme-version_0.9.12 && ./dist.sh gen && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr/local-other .. && make && make install

FROM schemers/${COMPILE_R7RS}
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    make \
    libffi8 \
    libgc1 \
    libssl3 \
    libuv1 \
    build-essential \
    libffi-dev \
    libmbedtls-dev
COPY --from=build /usr/local-other /usr/local-other
ENV PATH=${PATH}:/usr/local-other/bin
RUN git clone https://gitea.scheme.org/Retropikzel/compile-r7rs.git --depth=1
RUN cd compile-r7rs && make && make install

