FROM schemers/chibi:head
RUN apt-get update && apt-get install -y docker.io gauche
RUN git clone https://codeberg.org/retropikzel/test-scheme.git --depth=1
WORKDIR /test-scheme
RUN make && make install
