FROM docker.io/debian
RUN apt-get update && apt-get -y install git ca-certificates build-essential
WORKDIR /build
RUN git clone https://github.com/ashinn/chibi-scheme.git --depth=1
WORKDIR /build/chibi-scheme
RUN make
RUN make install
