(package
  (name (retropikzel pffi))
  (authors "Retropikzel")
  (maintainers "Retropikzel")
  (homepage "https://git.sr.ht/~retropikzel/r7rs-pffi")
  (manual "README.md")
  (description "Portable Foreign Function Interface for R7RS schemes")
  (keywords 'ffi)
  (license 'lgpl)
  (version "0.6.0")
  (test "test.scm")
  (library
    (name (retropikzel pffi))
    (path "retropikzel/pffi.sld")
    (depends)
    (platforms linux windows)))
