(package
  (name (foreign c))
  (authors "Retropikzel <retropikzel@iki.fi>")
  (maintainers "Retropikzel <retropikzel@iki.fi>")
  (homepage "https://git.sr.ht/~retropikzel/foreign-c")
  (manual "README.md")
  (description "Portable Foreign Function Interface for R7RS schemes")
  (keywords 'ffi)
  (license 'lgpl)
  (version "0.10.0")
  (test "test.scm")
  (library
    (name (foreign c))
    (path "foreign/c.sld")
    (depends)
    (platforms linux windows)))
