(cond-expand
  (kawa
    (define (argument->native-value value type)
      (cond ((c-bytevector? value)
             (c-bytevector-pointer value))
            ((equal? type 'i8)
             (java.lang.Integer value))
            ((equal? type 'u8)
             (java.lang.Integer value))
            ((equal? type 'i16)
             (java.lang.Integer value))
            ((equal? type 'u16)
             (java.lang.Integer value))
            ((equal? type 'i32)
             (java.lang.Integer value))
            ((equal? type 'u32)
             (java.lang.Integer value))
            ((equal? type 'i64)
             (java.lang.Integer value))
            ((equal? type 'u64)
             (java.lang.Integer value))
            ((equal? type 'char)
             (java.lang.Char value))
            ((equal? type 'uchar)
             (java.lang.Char value))
            ((equal? type 'short)
             (java.lang.Short value))
            ((equal? type 'ushort)
             (java.lang.Short value))
            ((equal? type 'int)
             (java.lang.Integer value))
            ((equal? type 'uint)
             (java.lang.Integer value))
            ((equal? type 'long)
             (java.lang.Long value))
            ((equal? type 'ulong)
             (java.lang.Long value))
            ((equal? type 'float)
             (java.lang.Float value))
            ((equal? type 'double)
             (java.lang.Double value))
            (else value))))
  (else
    (define (argument->native-value value)
      (if (c-bytevector? value)
        (c-bytevector-pointer value)
        value))))
