(define-syntax call-with-address-of
  (syntax-rules ()
    ((_ cbv thunk)
     (let ((address-cbv (make-c-bytevector (c-type-size 'pointer))))
       (c-bytevector-set! address-cbv 'pointer 0 cbv)
       (when (not (c-bytevector? cbv))
         (error "call-with-address-of: cbv argument must be c-bytevector" cbv))
       (when (not (procedure? thunk))
         (error "call-with-address-of: thunk argument must be procedure" thunk))
       (let ((result (apply thunk (list address-cbv))))
         (set! cbv (c-bytevector-ref address-cbv 'pointer 0))
         (c-bytevector-free address-cbv)
         result)))))
