(define size-of-type
  (lambda (type)
    (cond ((eq? type 'i8) 1)
          ((eq? type 'u8) 1)
          ((eq? type 'i16) 2)
          ((eq? type 'u16) 2)
          ((eq? type 'i32) 4)
          ((eq? type 'u32) 4)
          ((eq? type 'i64) 8)
          ((eq? type 'u64) 8)
          ((eq? type 'char) 1)
          ((eq? type 'uchar) 1)
          ((eq? type 'short) mosh-size-of-short)
          ((eq? type 'ushort) mosh-size-of-unsigned-short)
          ((eq? type 'int) mosh-size-of-int)
          ((eq? type 'uint) mosh-size-of-unsigned-int)
          ((eq? type 'long) mosh-size-of-long)
          ((eq? type 'ulong) mosh-size-of-unsigned-long)
          ((eq? type 'float) mosh-size-of-float)
          ((eq? type 'double) mosh-size-of-double)
          ((eq? type 'pointer) mosh-size-of-pointer)
          ((eq? type 'void) 0)
          (else #f))))

(define align-of-type
  (lambda (type)
    (cond ((eq? type 'i8) 1)
          ((eq? type 'u8) 1)
          ((eq? type 'i16) 2)
          ((eq? type 'u16) 2)
          ((eq? type 'i32) 4)
          ((eq? type 'u32) 4)
          ((eq? type 'i64) 8)
          ((eq? type 'u64) 8)
          ((eq? type 'char) 1)
          ((eq? type 'uchar) 1)
          ((eq? type 'short) mosh-align-of-short)
          ((eq? type 'ushort) mosh-align-of-short)
          ((eq? type 'int) mosh-align-of-int)
          ((eq? type 'uint) mosh-align-of-int)
          ((eq? type 'long) mosh-align-of-long)
          ((eq? type 'ulong) mosh-align-of-unsigned-long)
          ((eq? type 'float) mosh-align-of-float)
          ((eq? type 'double) mosh-align-of-double)
          ((eq? type 'pointer) mosh-align-of-void*)
          ((eq? type 'void) 0)
          (else #f))))

(define shared-object-load
  (lambda (path options)
    (mosh-open-shared-library path)))

(define c-u8-set! mosh-pointer-set-c-uint8!)
(define c-u8-ref mosh-pointer-ref-c-uint8)
(define c-pointer-set!
  (lambda (pointer offset value)
    (mosh-pointer-set-c-pointer! pointer offset value)))
(define c-pointer-ref
  (lambda (pointer offset)
    (mosh-pointer-ref-c-pointer pointer offset)))

(define type->native-type
  (lambda (type)
    (cond ((equal? type 'i8) 'int8_t)
          ((equal? type 'u8) 'uint8_t)
          ((equal? type 'i16) 'int16_t)
          ((equal? type 'u16) 'uint16_t)
          ((equal? type 'i32) 'int32_t)
          ((equal? type 'u32) 'uint32_t)
          ((equal? type 'i64) 'int64_t)
          ((equal? type 'u64) 'uint64_t)
          ((equal? type 'char) 'char)
          ((equal? type 'uchar) 'char)
          ((equal? type 'short) 'short)
          ((equal? type 'ushort) 'unsigned-short)
          ((equal? type 'int) 'int)
          ((equal? type 'uint) 'unsigned-int)
          ((equal? type 'long) 'long)
          ((equal? type 'ulong) 'unsigned-long)
          ((equal? type 'float) 'float)
          ((equal? type 'double) 'double)
          ((equal? type 'pointer) 'void*)
          ((equal? type 'void) 'void)
          ((equal? type 'callback) 'void*)
          (else (error "type->native-type -- No such type" type)))))

(define-syntax define-c-procedure
  (syntax-rules ()
    ((_ scheme-name shared-object c-name return-type argument-types)
     (define scheme-name
       (lambda args
         (let ((internal
                 (mosh-make-c-function shared-object
                                  (type->native-type return-type)
                                  c-name
                                  (map type->native-type argument-types))))
           (if (equal? return-type 'pointer)
             (internal-make-c-bytevector (apply internal (map value->native-value args)))
             (apply internal (map value->native-value args)))))))))

(define (c-null) (mosh-integer->pointer 0))
(define c-null? mosh-pointer-null?)
