(define (size-of-type type)
  (cond ((eq? type 'i8) sagittarius-size-of-int8_t)
        ((eq? type 'u8) sagittarius-size-of-uint8_t)
        ((eq? type 'i16) sagittarius-size-of-int16_t)
        ((eq? type 'u16) sagittarius-size-of-uint16_t)
        ((eq? type 'i32) sagittarius-size-of-int32_t)
        ((eq? type 'u32) sagittarius-size-of-uint32_t)
        ((eq? type 'i64) sagittarius-size-of-int64_t)
        ((eq? type 'u64) sagittarius-size-of-uint64_t)
        ((eq? type 'char) sagittarius-size-of-char)
        ((eq? type 'uchar) sagittarius-size-of-char)
        ((eq? type 'short) sagittarius-size-of-short)
        ((eq? type 'ushort) sagittarius-size-of-unsigned-short)
        ((eq? type 'int) sagittarius-size-of-int)
        ((eq? type 'uint) sagittarius-size-of-unsigned-int)
        ((eq? type 'long) sagittarius-size-of-long)
        ((eq? type 'ulong) sagittarius-size-of-unsigned-long)
        ((eq? type 'float) sagittarius-size-of-float)
        ((eq? type 'double) sagittarius-size-of-double)
        ((eq? type 'pointer) sagittarius-size-of-void*)
        ((eq? type 'void) 0)
        (else #f)))

(define (align-of-type type)
  (cond ((eq? type 'i8) sagittarius-align-of-int8_t)
        ((eq? type 'u8) sagittarius-align-of-uint8_t)
        ((eq? type 'i16) sagittarius-align-of-int16_t)
        ((eq? type 'u16) sagittarius-align-of-uint16_t)
        ((eq? type 'i32) sagittarius-align-of-int32_t)
        ((eq? type 'u32) sagittarius-align-of-uint32_t)
        ((eq? type 'i64) sagittarius-align-of-int64_t)
        ((eq? type 'u64) sagittarius-align-of-uint64_t)
        ((eq? type 'char) sagittarius-align-of-char)
        ((eq? type 'uchar) sagittarius-align-of-char)
        ((eq? type 'short) sagittarius-align-of-short)
        ((eq? type 'ushort) sagittarius-align-of-unsigned-short)
        ((eq? type 'int) sagittarius-align-of-int)
        ((eq? type 'uint) sagittarius-align-of-unsigned-int)
        ((eq? type 'long) sagittarius-align-of-long)
        ((eq? type 'ulong) sagittarius-align-of-unsigned-long)
        ((eq? type 'float) sagittarius-align-of-float)
        ((eq? type 'double) sagittarius-align-of-double)
        ((eq? type 'pointer) sagittarius-align-of-void*)
        ((eq? type 'void) 0)
        (else #f)))

(define (shared-object-load path options)
  (sagittarius-open-shared-library path))

(define (type->native-type type)
  (cond ((equal? type 'i8) 'int8_t)
        ((equal? type 'u8) 'uint8_t)
        ((equal? type 'i16) 'int16_t)
        ((equal? type 'u16) 'uint16_t)
        ((equal? type 'i32) 'int32_t)
        ((equal? type 'u32) 'uint32_t)
        ((equal? type 'i64) 'int64_t)
        ((equal? type 'u64) 'uint64_t)
        ((equal? type 'char) 'char)
        ((equal? type 'uchar) 'char)
        ((equal? type 'short) 'short)
        ((equal? type 'ushort) 'unsigned-short)
        ((equal? type 'int) 'int)
        ((equal? type 'uint) 'unsigned-int)
        ((equal? type 'long) 'long)
        ((equal? type 'ulong) 'unsigned-long)
        ((equal? type 'float) 'float)
        ((equal? type 'double) 'double)
        ((equal? type 'pointer) 'void*)
        ((equal? type 'void) 'void)
        (else #f)))

(define-syntax define-c-procedure
  (syntax-rules ()
    ((_ scheme-name shared-object c-name return-type argument-types)
     (define scheme-name
       (lambda args
         (let ((internal (sagittarius-make-c-function shared-object
                                          (type->native-type return-type)
                                          c-name
                                          (map type->native-type argument-types))))
           (if (equal? return-type 'pointer)
             (internal-make-c-bytevector (apply internal (map value->native-value args)))
             (apply internal (map value->native-value args)))))))))

(define c-u8-set! sagittarius-pointer-set-c-uint8_t!)
(define c-u8-ref sagittarius-pointer-ref-c-uint8_t)
(define c-pointer-set! sagittarius-pointer-set-c-pointer!)
(define c-pointer-ref sagittarius-pointer-ref-c-pointer)

(define c-null sagittarius-empty-pointer)
(define c-null? sagittarius-null-pointer?)


