(define (c-integer-type? type)
  (or (equal? type 'i8)
      (equal? type 'u8)
      (equal? type 'i16)
      (equal? type 'u16)
      (equal? type 'i32)
      (equal? type 'u32)
      (equal? type 'i64)
      (equal? type 'u64)
      (equal? type 'short)
      (equal? type 'ushort)
      (equal? type 'int)
      (equal? type 'uint)
      (equal? type 'long)
      (equal? type 'ulong)
      (equal? type 'llong)
      (equal? type 'ullong)))

(define (c-char-type? type)
  (or (equal? type 'char)
      (equal? type 'uchar)))

(define (c-signed-type? type)
  (or (equal? type 'i8)
      (equal? type 'i16)
      (equal? type 'i32)
      (equal? type 'i64)
      (equal? type 'char)
      (equal? type 'short)
      (equal? type 'int)
      (equal? type 'long)
      (equal? type 'llong)
      (equal? type 'float)
      (equal? type 'double)
      (equal? type 'ldouble)))

(define (c-float-type? type) (equal? type 'float))

(define (c-double-type? type)
  (or (equal? type 'double)
      (equal? type 'ldouble)))

(define (c-pointer-type? type) (equal? type 'pointer))

(define (c-type-size type)
  (cond ((equal? type 'void) 0)
        ((equal? type 'i8) 1)
        ((equal? type 'u8) 1)
        ((equal? type 'i16) 2)
        ((equal? type 'u16) 2)
        ((equal? type 'i32) 4)
        ((equal? type 'u32) 4)
        ((equal? type 'i64) 8)
        ((equal? type 'u64) 8)
        ((equal? type 'char) 1)
        ((equal? type 'uchar) 1)
        ((equal? type 'short) 2)
        ((equal? type 'ushort) 2)
        ((equal? type 'int) 4)
        ((equal? type 'uint) 4)
        ((equal? type 'long) 8)
        ((equal? type 'ulong) 8)
        ((equal? type 'llong) 16)
        ((equal? type 'ullong) 16)
        ((equal? type 'float) 4)
        ((equal? type 'double) 8)
        ((equal? type 'ldouble) 16)
        ((equal? type 'pointer) 8)
        ((c-array-type? type) (internal-array-type-size type))
        ((c-struct-type? type) (c-struct-type-size type))
        ;((assoc type c-struct-type-list) (c-type-size (cdr (assoc type c-struct-type-list))))
        (else (error "c-type-size: Unknown type" type))))

(define c-type-size+ (lambda types (apply + (map c-type-size types))))
(define (c-type-size* type n) (* (c-type-size type) n))
(define c-type-size- (lambda types (apply - (map c-type-size types))))

(define (c-type-align type)
  (cond ((equal? type 'i8) 1)
        ((equal? type 'u8) 1)
        ((equal? type 'i16) 2)
        ((equal? type 'u16) 2)
        ((equal? type 'i32) 4)
        ((equal? type 'u32) 4)
        ((equal? type 'i64) 8)
        ((equal? type 'u64) 8)
        ((equal? type 'char) 1)
        ((equal? type 'uchar) 1)
        ((equal? type 'short) 2)
        ((equal? type 'ushort) 2)
        ((equal? type 'int) 4)
        ((equal? type 'uint) 4)
        ((equal? type 'long) 8)
        ((equal? type 'ulong) 8)
        ((equal? type 'llong) 16)
        ((equal? type 'ullong) 16)
        ((equal? type 'float) 4)
        ((equal? type 'double) 8)
        ((equal? type 'ldouble) 16)
        ((equal? type 'pointer) 8)
        ((c-array-type? type) (internal-array-type-size type))
        ((c-struct-type? type) (c-struct-type-size type))
        ;((assoc type c-struct-type-list) (c-type-size (cdr (assoc type c-struct-type-list))))
        (else (error "c-type-align: Unknown type" type))))

(define c-type-align+ (lambda types (apply + (map c-type-align types))))
(define (c-type-align* type n) (* (c-type-align type) n))
(define c-type-align- (lambda types (apply - (map c-type-align types))))
