(define size-of-type
  (lambda (type)
    (cond ((eq? type 'i8) (gauche:size-of-type 'int8))
          ((eq? type 'u8) (gauche:size-of-type 'uint8))
          ((eq? type 'i16) (gauche:size-of-type 'int16))
          ((eq? type 'u16) (gauche:size-of-type 'uint16))
          ((eq? type 'i32) (gauche:size-of-type 'int32))
          ((eq? type 'u32) (gauche:size-of-type 'uint32))
          ((eq? type 'i64) (gauche:size-of-type 'int64))
          ((eq? type 'u64) (gauche:size-of-type 'uint64))
          ((eq? type 'char) (gauche:size-of-type 'char))
          ((eq? type 'uchar) (gauche:size-of-type 'char))
          ((eq? type 'short) (gauche:size-of-type 'short))
          ((eq? type 'ushort) (gauche:size-of-type 'unsigned-short))
          ((eq? type 'int) (gauche:size-of-type 'int))
          ((eq? type 'uint) (gauche:size-of-type 'unsigned-int))
          ((eq? type 'long) (gauche:size-of-type 'long))
          ((eq? type 'ulong) (gauche:size-of-type 'unsigned-long))
          ((eq? type 'float) (gauche:size-of-type 'float))
          ((eq? type 'double) (gauche:size-of-type 'double))
          ((eq? type 'pointer) (gauche:size-of-type 'pointer)))))

(define align-of-type
  (lambda (type)
    (cond ((eq? type 'i8) (gauche:align-of-type 'int8))
          ((eq? type 'u8) (gauche:align-of-type 'uint8))
          ((eq? type 'i16) (gauche:align-of-type 'int16))
          ((eq? type 'u16) (gauche:align-of-type 'uint16))
          ((eq? type 'i32) (gauche:align-of-type 'int32))
          ((eq? type 'u32) (gauche:align-of-type 'uint32))
          ((eq? type 'i64) (gauche:align-of-type 'int64))
          ((eq? type 'u64) (gauche:align-of-type 'uint64))
          ((eq? type 'char) (gauche:align-of-type 'char))
          ((eq? type 'uchar) (gauche:align-of-type 'char))
          ((eq? type 'short) (gauche:align-of-type 'short))
          ((eq? type 'ushort) (gauche:align-of-type 'unsigned-short))
          ((eq? type 'int) (gauche:align-of-type 'int))
          ((eq? type 'uint) (gauche:align-of-type 'unsigned-int))
          ((eq? type 'long) (gauche:align-of-type 'long))
          ((eq? type 'ulong) (gauche:align-of-type 'unsigned-long))
          ((eq? type 'float) (gauche:align-of-type 'float))
          ((eq? type 'double) (gauche:align-of-type 'double))
          ((eq? type 'pointer) (gauche:align-of-type 'pointer)))))

(define shared-object-load
  (lambda (path options)
    (if (null? options)
      (open-shared-library path)
      (open-shared-library path (cadr (assoc 'additional-versions options))))))

(define type->native-type
  (lambda (type)
    (cond ((equal? type 'i8) 'int8)
          ((equal? type 'u8) 'uint8)
          ((equal? type 'i16) 'int16)
          ((equal? type 'u16) 'uint16)
          ((equal? type 'i32) 'int32)
          ((equal? type 'u32) 'uint32)
          ((equal? type 'i64) 'int64)
          ((equal? type 'u64) 'uint64)
          ((equal? type 'char) 'char)
          ((equal? type 'uchar) 'char)
          ((equal? type 'short) 'short)
          ((equal? type 'ushort) 'unsigned-short)
          ((equal? type 'int) 'int)
          ((equal? type 'uint) 'unsigned-int)
          ((equal? type 'long) 'long)
          ((equal? type 'ulong) 'unsigned-long)
          ((equal? type 'float) 'float)
          ((equal? type 'double) 'double)
          ((equal? type 'pointer) 'pointer)
          ((equal? type 'void) 'pointer)
          ((equal? type 'callback) 'callback)
          (else #f))))

(define-syntax define-c-procedure
  (syntax-rules ()
    ((_ scheme-name shared-object c-name return-type argument-types)
     (define scheme-name
       (make-c-function shared-object
                        (type->native-type return-type)
                        c-name
                        (map type->native-type argument-types))))))

(define c-u8-set! pointer-set-c-uint8!)
(define c-u8-ref pointer-ref-c-uint8)
(define c-pointer-set! pointer-set-c-pointer!)
(define c-pointer-ref pointer-ref-c-pointer)
;(define make-c-null null-pointer)
(define c-null? null-pointer?)


