(define (c-type-size type)
  (cond ((not (symbol? type)) (error "c-type-size: Type must be symbol" type))
        ((symbol=? type 'void) 0)
        ((or (symbol=? type 'i8)
             (symbol=? type 'u8)
             (symbol=? type 'i16)
             (symbol=? type 'u16)
             (symbol=? type 'i32)
             (symbol=? type 'u32)
             (symbol=? type 'i64)
             (symbol=? type 'u64)
             (symbol=? type 'char)
             (symbol=? type 'uchar)
             (symbol=? type 'short)
             (symbol=? type 'ushort)
             (symbol=? type 'int)
             (symbol=? type 'uint)
             (symbol=? type 'long)
             (symbol=? type 'ulong)
             (symbol=? type 'float)
             (symbol=? type 'double)
             (symbol=? type 'pointer))
         (size-of-type type))
        (else (error "Unknown type" type))))

(define (c-type-align type)
  (cond ((not (symbol? type)) (error "c-type-align: Type must be symbol" type))
        ((symbol=? type 'void) 0)
        ((or (symbol=? type 'i8)
             (symbol=? type 'u8)
             (symbol=? type 'i16)
             (symbol=? type 'u16)
             (symbol=? type 'i32)
             (symbol=? type 'u32)
             (symbol=? type 'i64)
             (symbol=? type 'u64)
             (symbol=? type 'char)
             (symbol=? type 'uchar)
             (symbol=? type 'short)
             (symbol=? type 'ushort)
             (symbol=? type 'int)
             (symbol=? type 'uint)
             (symbol=? type 'long)
             (symbol=? type 'ulong)
             (symbol=? type 'float)
             (symbol=? type 'double)
             (symbol=? type 'pointer))
         (align-of-type type))
        (else (error "Unknown type" type))))
