(cond-expand
  (kawa
    (define (value->native-value value type)
      (cond ((c-bytevector? value)
             (c-bytevector-pointer value))
            ((equal? type 'byte)
             (java.lang.Byte value))
            ((equal? type 'i8)
             (java.lang.Integer value))
            ((equal? type 'u8)
             (java.lang.Integer value))
            ((equal? type 'short)
             (java.lang.Short value))
            ((equal? type 'unsigned-short)
             (java.lang.Short value))
            ((equal? type 'int)
             (java.lang.Integer value))
            ((equal? type 'unsigned-int)
             (java.lang.Integer value))
            ((equal? type 'long)
             (java.lang.Long value))
            ((equal? type 'unsigned-long)
             (java.lang.Long value))
            ((equal? type 'float)
             (java.lang.Float value))
            ((equal? type 'double)
             (java.lang.Double value))
            ((equal? type 'char)
             (java.lang.Char value))
            (else value))))
  (else
    (define (value->native-value value)
      (if (c-bytevector? value)
        (c-bytevector-pointer value)
        value))))
