ARG COMPILE_R7RS=chibi
FROM debian:bookworm AS build
RUN apt-get update && apt-get install -y wget build-essential make cmake libgc-dev zlib1g-dev libffi-dev libssl-dev git
RUN git clone https://github.com/Retropikzel/chibi-scheme.git --branch=snow-chibi-foreign-depends
RUN cd chibi-scheme && make PREFIX=/usr/local-other && make PREFIX=/usr/local-other install
RUN wget https://github.com/ktakashi/sagittarius-scheme/releases/download/v0.9.13/sagittarius-0.9.13.tar.gz && tar -xf version_0.9.13.tar.gz
RUN cd sagittarius-scheme-version_0.9.12 && ./dist.sh gen && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr/local-other .. && make && make install

FROM schemers/${COMPILE_R7RS}
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    make \
    libffi8 \
    libgc1 \
    libssl3 \
    libuv1 \
    build-essential \
    libffi-dev \
    libmbedtls-dev \
    markdown
COPY --from=build /usr/local-other /usr/local-other
RUN ln -sf /usr/local/bin/chibi-scheme /usr/local/bin/chibi
RUN rm -rf /usr/local/bin/snow-chibi
ENV PATH=${PATH}:/usr/local-other/bin
RUN git clone https://gitea.scheme.org/Retropikzel/compile-r7rs.git --depth=1
RUN cd compile-r7rs && make && make install

