FROM schemers/${COMPILE_R7RS}
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    make \
    libffi8 \
    libgc1 \
    libssl3 \
    libuv1 \
    build-essential \
    libffi-dev \
    libmbedtls-dev \
    chicken-bin
RUN git clone https://gitea.scheme.org/Retropikzel/compile-r7rs.git --depth=1
RUN cd compile-r7rs && make && make install

