ARG SCHEME=chibi
FROM schemers/chicken AS build
RUN apt-get update && apt-get install -y git
RUN git clone https://gitea.scheme.org/Retropikzel/compile-r7rs.git --depth=1
RUN cd compile-r7rs && make && make install

ARG SCHEME=chibi
FROM schemers/${SCHEME}
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    make \
    libffi8 \
    libgc1 \
    libssl3 \
    libuv1 \
    build-essential \
    libffi-dev \
    libmbedtls-dev \
    markdown \
    pandoc \
    weasyprint
COPY --from=build /usr/local /usr/local
RUN git clone https://github.com/ashinn/chibi-scheme.git --depth=1
RUN cd chibi-scheme && make && make install
ARG SCHEME=chibi
ENV COMPILE_R7RS=${SCHEME}
RUN mkdir -p ${HOME}/.snow && echo "()" > ${HOME}/.snow/config.scm
