ARG SCHEME=chibi
FROM debian:bookworm AS build
RUN apt-get update && apt-get install -y git make chicken-bin build-essential
RUN chicken-install r7rs
RUN git clone https://github.com/Retropikzel/compile-r7rs.git --depth=1
RUN cd compile-r7rs && make && make install
RUN git clone https://github.com/ashinn/chibi-scheme.git --depth=1
RUN cd chibi-scheme && make && make PREFIX=/usr/local-other install

ARG SCHEME=chibi
FROM schemers/${SCHEME}:head
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    make \
    libffi8 \
    libgc1 \
    libssl3 \
    libuv1 \
    build-essential \
    libffi-dev \
    libmbedtls-dev \
    markdown \
    pandoc \
    weasyprint
COPY --from=build /usr/local-other /usr/local-other
ENV PATH=/usr/local-other/bin:${PATH}
COPY --from=build /usr/local/bin/compile-r7rs /usr/local/bin/compile-r7rs
ARG SCHEME=chibi
ENV COMPILE_R7RS=${SCHEME}
RUN mkdir -p ${HOME}/.snow && echo "()" > ${HOME}/.snow/config.scm
ENV GUILE_AUTO_COMPILE=0
