ARG SCHEME=chibi
ARG IMAGE=chibi:head
FROM schemers/${IMAGE}
RUN apt-get update && apt-get install -y \
    build-essential \
    make \
    libffi-dev \
    pandoc \
    libmbedtls-dev
RUN mkdir -p ${HOME}/.snow && echo "()" > ${HOME}/.snow/config.scm
COPY --from=retropikzel1/compile-r7rs /opt/compile-r7rs /opt/compile-r7rs
ENV PATH=/opt/compile-r7rs/bin:${PATH}
ARG SCHEME=chibi
ENV COMPILE_R7RS=${SCHEME}
ENV GUILE_AUTO_COMPILE=0
RUN git clone https://github.com/ashinn/chibi-scheme.git --depth=1
RUN cd chibi-scheme && make && make install
