/* Generated by genstub.  Do not edit. */
#include <gauche.h>
#include <stdio.h>
#include <ffi.h>
void Scm_Init_gauche_primitives_gauche(void) { puts("Hello from init"); }
extern ScmObj hello() { return Scm_MakeInteger(1); }
static ScmObj gauche_primitives_2egauche_hello(ScmObj*, int, void*);
static SCM_DEFINE_SUBRX(gauche_primitives_2egauche_hello__STUB, 0, 0,0, SCM_FALSE,SCM_SUBR_IMMEDIATE_ARG, gauche_primitives_2egauche_hello, NULL, NULL);

#if defined(__CYGWIN__) || defined(GAUCHE_WINDOWS)
#define SCM_CGEN_CONST /*empty*/
#else
#define SCM_CGEN_CONST const
#endif
static SCM_CGEN_CONST struct scm__scRec {
  ScmString d2840[5];
} scm__sc SCM_UNUSED = {
  {   /* ScmString d2840 */
      SCM_STRING_CONST_INITIALIZER("hello", 5, 5),
      SCM_STRING_CONST_INITIALIZER("source-info", 11, 11),
      SCM_STRING_CONST_INITIALIZER("foreign/c/gauche-primitives.gauche.stub", 39, 39),
      SCM_STRING_CONST_INITIALIZER("->", 2, 2),
      SCM_STRING_CONST_INITIALIZER("<top>", 5, 5),
  },
};
static struct scm__rcRec {
  ScmPair d2852[5] SCM_ALIGN_PAIR;
  ScmObj d2851[11];
} scm__rc SCM_UNUSED = {
  {   /* ScmPair d2852 */
       { SCM_NIL, SCM_NIL },
       { SCM_MAKE_INT(8U), SCM_NIL},
       { SCM_OBJ(&scm__sc.d2840[2]), SCM_OBJ(&scm__rc.d2852[1])},
       { SCM_UNDEFINED, SCM_OBJ(&scm__rc.d2852[2])},
       { SCM_OBJ(&scm__rc.d2852[3]), SCM_NIL},
  },
  {   /* ScmObj d2851 */
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_OBJ(SCM_CLASS_STATIC_TAG(Scm_VectorClass)) /* <vector> */,
    SCM_VECTOR_SIZE_SLOT_INITIALIZER(4, FALSE),
    SCM_MAKE_INT(1U),
    SCM_FALSE,
    SCM_UNDEFINED,
    SCM_UNDEFINED,
  },
};

static ScmObj gauche_primitives_2egauche_hello(ScmObj *SCM_FP SCM_UNUSED, int SCM_ARGCNT SCM_UNUSED, void *data_ SCM_UNUSED)
{
  SCM_ENTER_SUBR("hello");
  {
{
ScmObj SCM_RESULT;
{SCM_RESULT=(hello());goto SCM_STUB_RETURN;}
goto SCM_STUB_RETURN;
SCM_STUB_RETURN:
SCM_RETURN(SCM_OBJ_SAFE(SCM_RESULT));
}
  }
}

void Scm_Init_gauche_primitives_2egauche(ScmModule *mod SCM_UNUSED){

  scm__rc.d2851[0] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d2840[0])),TRUE); /* hello */
  scm__rc.d2851[1] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d2840[1])),TRUE); /* source-info */
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d2852[3]), scm__rc.d2851[1]);
  scm__rc.d2851[2] = Scm_MakeExtendedPair(scm__rc.d2851[0], SCM_NIL, SCM_OBJ(&scm__rc.d2852[4]));
  scm__rc.d2851[3] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d2840[3])),TRUE); /* -> */
  scm__rc.d2851[4] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d2840[4])),TRUE); /* <top> */
  ((ScmObj*)SCM_OBJ(&scm__rc.d2851[5]))[4] = scm__rc.d2851[3];
  ((ScmObj*)SCM_OBJ(&scm__rc.d2851[5]))[5] = scm__rc.d2851[4];
  Scm_MakeBinding(SCM_MODULE(mod), SCM_SYMBOL(SCM_INTERN("hello")), SCM_OBJ(&gauche_primitives_2egauche_hello__STUB), 0);
  gauche_primitives_2egauche_hello__STUB.common.info = scm__rc.d2851[2];
  gauche_primitives_2egauche_hello__STUB.common.typeHint = SCM_OBJ(&scm__rc.d2851[5]);
  SCM_VECTOR_ELEMENT(SCM_OBJ(&scm__rc.d2851[5]), 1) = SCM_MODULE(mod)->name;
}
