pipeline {
    agent {
        dockerfile {
            filename 'dockerfiles/jenkins'
            dir '.'
            args '--privileged -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    options {
            buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }

    stages {
        {{#script-implementations}}
        stage('{{.}} script') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh 'make SCHEME={{.}} test-script-docker'
                }
            }
        }
        {{/script-implementations}}
        {{#compiler-implementations}}
        stage('{{.}} compile') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh 'make SCHEME={{.}} test-compile-docker'
                }
            }
        }
        {{/compiler-implementations}}
    }
}
