(in-module foreign.c.primitives.gauche)

(inline-stub
 (.include "foreign-c-primitives-gauche.h")
 (define-cproc size-of-int8 () size_of_int8)
 (define-cproc size-of-uint8 () size_of_uint8)
 (define-cproc size-of-int16 () size_of_int16)
 (define-cproc size-of-uint16 () size_of_int16)
 (define-cproc size-of-int32 () size_of_int32)
 (define-cproc size-of-uint32 () size_of_int32)
 (define-cproc size-of-int64 () size_of_int64)
 (define-cproc size-of-uint64 () size_of_int64)
 (define-cproc size-of-char () size_of_char)
 (define-cproc size-of-unsigned-char () size_of_unsigned_char)
 (define-cproc size-of-short () size_of_short)
 (define-cproc size-of-unsigned-short () size_of_unsigned_short)
 (define-cproc size-of-int () size_of_int)
 (define-cproc size-of-unsigned-int () size_of_unsigned_int)
 (define-cproc size-of-long () size_of_long)
 (define-cproc size-of-unsigned-long () size_of_unsigned_long)
 (define-cproc size-of-float () size_of_float)
 (define-cproc size-of-double () size_of_double)
 (define-cproc size-of-string () size_of_string)
 (define-cproc size-of-pointer () size_of_pointer)
 (define-cproc size-of-void () size_of_void)
 (define-cproc shared-object-load (path::<string> options) shared_object_load)
 ;(define-cproc pointer-null () pointer_null)
 ;(define-cproc pointer-null? (pointer) is_pointer_null)
 ;(define-cproc pointer-allocate (size::<int>) pointer_allocate)
 ;(define-cproc pointer-address (object) pointer_address)
 (define-cproc pointer? (pointer) is_pointer)
 ;(define-cproc pointer-free (pointer) pointer_free)

 ;(define-cproc pointer-set-int8! (pointer offset::<int> value::<int8>) pointer_set_int8)
 (define-cproc pointer-set-uint8! (pointer offset::<int> value::<int8>) pointer_set_uint8)
 ;(define-cproc pointer-set-int16! (pointer offset::<int> value::<int16>) pointer_set_int16)
 ;(define-cproc pointer-set-uint16! (pointer offset::<int> value::<int16>) pointer_set_uint16)
 ;(define-cproc pointer-set-int32! (pointer offset::<int> value::<int32>) pointer_set_int32)
 ;(define-cproc pointer-set-uint32! (pointer offset::<int> value::<int32>) pointer_set_uint32)
 ;(define-cproc pointer-set-int64! (pointer offset::<int> value::<int64>) pointer_set_int64)
 ;(define-cproc pointer-set-uint64! (pointer offset::<int> value::<int64>) pointer_set_uint64)
 ;(define-cproc pointer-set-char! (pointer offset::<int> value::<char>) pointer_set_char)
 ;(define-cproc pointer-set-unsigned-char! (pointer offset::<int> value::<char>) pointer_set_unsigned_char)
 ;(define-cproc pointer-set-short! (pointer offset::<int> value::<short>) pointer_set_short)
 ;(define-cproc pointer-set-unsigned-short! (pointer offset::<int> value::<short>) pointer_set_unsigned_short)
 ;(define-cproc pointer-set-int! (pointer offset::<int> value::<int>) pointer_set_int)
 ;(define-cproc pointer-set-unsigned-int! (pointer offset::<int> value::<int>) pointer_set_unsigned_int)
 ;(define-cproc pointer-set-long! (pointer offset::<int> value::<long>) pointer_set_long)
 ;(define-cproc pointer-set-unsigned-long! (pointer offset::<int> value::<long>) pointer_set_unsigned_long)
 ;(define-cproc pointer-set-float! (pointer offset::<int> value::<float>) pointer_set_float)
 ;(define-cproc pointer-set-double! (pointer offset::<int> value::<double>) pointer_set_double)
 (define-cproc pointer-set-pointer! (pointer offset::<int> value) pointer_set_pointer)

 ;(define-cproc pointer-get-int8 (pointer offset::<int>) pointer_get_int8)
 (define-cproc pointer-get-uint8 (pointer offset::<int>) pointer_get_uint8)
 ;(define-cproc pointer-get-int16 (pointer offset::<int>) pointer_get_int16)
 ;(define-cproc pointer-get-uint16 (pointer offset::<int>) pointer_get_uint16)
 ;(define-cproc pointer-get-int32 (pointer offset::<int>) pointer_get_int32)
 ;(define-cproc pointer-get-uint32 (pointer offset::<int>) pointer_get_uint32)
 ;(define-cproc pointer-get-int64 (pointer offset::<int>) pointer_get_int64)
 ;(define-cproc pointer-get-uint64 (pointer offset::<int>) pointer_get_uint64)
 ;(define-cproc pointer-get-char (pointer offset::<int>) pointer_get_char)
 ;(define-cproc pointer-get-unsigned-char (pointer offset::<int>) pointer_get_unsigned_char)
 ;(define-cproc pointer-get-short (pointer offset::<int>) pointer_get_short)
 ;(define-cproc pointer-get-unsigned-short (pointer offset::<int>) pointer_get_unsigned_short)
 ;(define-cproc pointer-get-int (pointer offset::<int>) pointer_get_int)
 ;(define-cproc pointer-get-unsigned-int (pointer offset::<int>) pointer_get_unsigned_int)
 ;(define-cproc pointer-get-long (pointer offset::<int>) pointer_get_long)
 ;(define-cproc pointer-get-unsigned-long (pointer offset::<int>) pointer_get_unsigned_long)
 ;(define-cproc pointer-get-float (pointer offset::<int>) pointer_get_float)
 ;(define-cproc pointer-get-double (pointer offset::<int>) pointer_get_double)
 (define-cproc pointer-get-pointer (pointer offset::<int>) pointer_get_pointer)

 (define-cproc dlerror () internal_dlerror)
 (define-cproc dlsym (shared-object c-name) internal_dlsym)
 (define-cproc internal-ffi-call (nargs rtype atypes fn rvalue avalues) internal_ffi_call)
 (define-cproc scheme-procedure-to-pointer (procedure) scheme_procedure_to_pointer)

 ;(define-cproc get-ffi-type-int8 () get_ffi_type_int8)
 ;(define-cproc get-ffi-type-uint8 () get_ffi_type_uint8)
 ;(define-cproc get-ffi-type-int16 () get_ffi_type_int16)
 ;(define-cproc get-ffi-type-uint16 () get_ffi_type_uint16)
 ;(define-cproc get-ffi-type-int32 () get_ffi_type_int32)
 ;(define-cproc get-ffi-type-uint32 () get_ffi_type_uint32)
 ;(define-cproc get-ffi-type-int64 () get_ffi_type_int64)
 ;(define-cproc get-ffi-type-uint64 () get_ffi_type_uint64)
 ;(define-cproc get-ffi-type-char () get_ffi_type_char)
 ;(define-cproc get-ffi-type-unsigned-char () get_ffi_type_unsigned_char)
 ;(define-cproc get-ffi-type-short () get_ffi_type_short)
 ;(define-cproc get-ffi-type-unsigned-short () get_ffi_type_unsigned_short)
 ;(define-cproc get-ffi-type-int () get_ffi_type_int)
 ;(define-cproc get-ffi-type-unsigned-int () get_ffi_type_unsigned_int)
 ;(define-cproc get-ffi-type-long () get_ffi_type_long)
 ;(define-cproc get-ffi-type-unsigned-long () get_ffi_type_unsigned_long)
 ;(define-cproc get-ffi-type-float () get_ffi_type_float)
 ;(define-cproc get-ffi-type-double () get_ffi_type_double)
 ;(define-cproc get-ffi-type-void() get_ffi_type_void)
 ;(define-cproc get-ffi-type-pointer () get_ffi_type_pointer)

 ;(define-cproc procedure-to-pointer (procedure) procedure_to_pointer)
 )
